version: "3.5"
services:
  grafana:
    image: grafana/grafana:7.2.1
    restart: always
    ports:
      - 3010:3000
    volumes:
      - ./plugins/:/var/lib/grafana/plugins/
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password

secrets:
  grafana_admin_password:
    file: ./secrets/.grafana_admin_password
